version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - pip install awscli
  build:
    commands:
      - echo "Deploying CloudFormation stack..."
      - aws cloudformation deploy \
          --template-file cfwithlambdaandapitemplate.yaml \
          --stack-name tagorestack \
          --capabilities CAPABILITY_NAMED_IAM
