AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation Stack to create resources using an external template.

Resources:
  TagoreStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://raw.githubusercontent.com/shivaram235vemula/AWSHandsOn/main/cfwithlambdaandapitemplate.yaml
      RoleARN: arn:aws:iam::975049951119:role/AWSCloudFormationStackSetAdministrationRole

Outputs:
  StackID:
    Description: The ID of the created stack
    Value: !Ref TagoreStack
